Humble_scheduler:
  ros__parameters:
    x_point:
      - 5.0
      - 5.0
      - 5.0
      - 5.0
      - 5.0
      - 5.0
      - 5.0
      - 5.0
      - 5.3
      - 5.6
      - 5.9
      - 6.2
      - 5.9
      - 5.6
      - 5.3
      - 5.0
      - 5.3
      - 5.6
      - 6.2
      - 5.9
      - 5.6
      - 5.0
    y_point:
      - 5.0
      - 5.6
      - 6.2
      - 6.8
      - 7.4
      - 8.0
      - 8.6
      - 9.2
      - 8.3
      - 8.6
      - 8.3
      - 8.0
      - 7.7
      - 7.4
      - 7.1
      - 6.8
      - 6.5
      - 6.2
      - 5.9
      - 5.6
      - 5.3
      - 5.0

    
