Foxy_scheduler:
  ros__parameters:
    x_point:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.35
      - 1.7
      - 2.05
      - 2.4
      - 2.75
      - 3.1
      - 1.35
      - 1.7
      - 2.05
      - 2.4
      - 9.9
    y_point:
      - 5.0
      - 5.35
      - 5.7
      - 6.05
      - 6.4
      - 6.75
      - 7.1
      - 7.45
      - 7.8
      - 8.15
      - 8.5
      - 8.85
      - 8.85
      - 8.85
      - 8.85
      - 8.85
      - 8.85
      - 8.85
      - 7.1
      - 7.1
      - 7.1
      - 7.1
      - 9.9
