Iron_scheduler:
  ros__parameters:
    x_point:
      - 8.0
      - 8.0
      - 8.0
      - 8.0
      - 8.0
      - 8.0
      - 8.0
      - 8.0
      - 8.6
      - 9.2
      - 9.8
      - 9.8
      - 9.8
      - 9.8
      - 9.8
      - 9.8
      - 9.8
      - 9.8
      - 9.2
      - 8.6
      - 8.0
    y_point:
      - 2.0
      - 2.6
      - 3.2
      - 3.8
      - 4.4
      - 5.0
      - 5.6
      - 6.2
      - 6.2
      - 6.2
      - 6.2
      - 5.6
      - 5.0
      - 4.4
      - 3.8
      - 3.2
      - 2.6
      - 2.0
      - 2.0
      - 2.0
      - 2.0



